# Generated by Django 4.1.6 on 2023-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('whatsapp', models.CharField(max_length=13)),
                ('nom', models.CharField(max_length=128)),
                ('nomAnimal', models.CharField(max_length=128)),
                ('ville', models.CharField(max_length=128)),
                ('date', models.DateField(null=True)),
                ('sexe', models.CharField(max_length=128, null=True)),
                ('age', models.CharField(max_length=128, null=True)),
                ('espece', models.CharField(max_length=128)),
                ('race', models.CharField(max_length=128, null=True)),
                ('Vacc', models.CharField(max_length=128, null=True)),
                ('couleur', models.CharField(max_length=128, null=True)),
                ('Motif', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('numéro', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('theme', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='imagePost')),
                ('blogPoster', models.CharField(blank=True, max_length=128)),
                ('joinPiece', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nom', models.CharField(max_length=128)),
                ('whatsapp', models.CharField(max_length=128)),
                ('ville', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('heure', models.TimeField(null=True)),
                ('status', models.CharField(max_length=128, null=True)),
                ('Message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField(null=True)),
                ('nom', models.CharField(max_length=128)),
                ('poste', models.CharField(max_length=128)),
                ('whatsapp', models.CharField(max_length=128, null=True)),
                ('twitter', models.CharField(max_length=128, null=True)),
                ('insta', models.CharField(max_length=128, null=True)),
                ('facebook', models.CharField(max_length=128, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='imagePoste')),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('contenu', models.TextField()),
                ('profession', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WhaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('lien', models.URLField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
