# Generated by Django 4.1.6 on 2023-08-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='lienVideoTravail',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='informations',
            name='lienVideoTuto',
            field=models.URLField(null=True),
        ),
    ]
