# Generated by Django 4.1.6 on 2023-08-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veto', '0002_informations_lienvideotravail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='informations',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
